all:
  hosts:
    yandex_vm:
      ansible_host: 51.250.42.25
      ansible_user: fateee
      ansible_ssh_private_key_file: /home/fateee/.ssh/yandex_ansible_key
      ansible_python_interpreter: /home/fateee/.local_ansible_env/bin/python