version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.1
    volumes:
      - ./loki-storage:/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Fate123!
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  moscow-time-app:
    image: fatee/moscow-time-app:latest
    container_name: moscow-time-app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
    command: flask run --host=0.0.0.0 --port=80

volumes:
  grafana-storage:
    driver: local
