apiVersion: v1
kind: Service
metadata:
  name: moscow-time-app-service
spec:
  selector:
    app.kubernetes.io/name: moscow-time-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
