apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moscow-time-app
  template:
    metadata:
      labels:
        app: moscow-time-app
    spec:
      containers:
      - name: moscow-time-app
        image: fatee/moscow-time-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MY_CATS_NAME
          valueFrom:
            secretKeyRef:
              name: secret-with-paws
              key: mycatsname
