apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: moscow-time-app-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: moscow-time-app
  endpoints:
    - port: "5000"
      interval: 15s
      path: "/metrics"
